version: "3.4"

x-defaults: &default
  restart: unless-stopped
  #  使用当前目录的 Dockerfile 来构建 docker 镜像
  build: .
  volumes:
    # 把当前目录(源代码目录) mount 到 docker container 的特定目录，那个目录就是 docker 环境里面进行编译的工作区间
    - .:/home/deploy/project
  networks:
    default:
      ipv4_address: 172.129.2.2

services:
  project:
    <<: *default
    container_name: C-Project-Build-env
    hostname: "C-Project-Build-Host"
    user: deploy
    working_dir: /home/deploy/project
    security_opt:
      - seccomp:unconfined
    command:
      bash -c "sudo service ssh restart"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.129.2.0/24